In [3]:
import math

In [4]:
import numpy as np


In [5]:
import pandas as pd


In [6]:
from scipy.spatial.distance import pdist, squareform

In [55]:
from scipy.spatial.distance import cdist

(a) Generate a data matrix D where the rows associate with each patient, and columns with patient’s ID, anxiety, alcohol_re, diabetes
and discharge rate; respectively.

In [7]:
# Read the CSV file
hospital_data = pd.read_csv('Hospital_dis_rates.csv')


In [8]:
# Create a data matrix D
D = hospital_data[['ID', 'Anxiety_Di', 'Alcohol_re', 'Diabetes', 'Discharges']].values

In [9]:
print(D)

[[1.00000000e+00 3.93608997e+02 2.70177604e+02 6.96378830e+01
  9.59010309e+03]
 [2.00000000e+00 1.32835014e+02 1.77863833e+02 4.35030452e+01
  8.95550862e+03]
 [3.00000000e+00 1.42476163e+02 1.47347143e+02 1.87200479e+01
  8.24013521e+03]
 [4.00000000e+00 2.01704730e+02 4.06662763e+02 9.01117386e+01
  1.33942835e+04]
 [5.00000000e+00 2.61648843e+02 2.50708822e+02 5.69584203e+01
  1.04867591e+04]
 [6.00000000e+00 2.40857947e+02 1.78445851e+02 6.09778296e+01
  8.93914409e+03]
 [7.00000000e+00 1.29593011e+02 2.45779848e+02 2.59922249e+01
  1.01502650e+04]
 [8.00000000e+00 1.23456790e+02 3.20987654e+02 1.80722892e+01
  9.59367531e+03]
 [9.00000000e+00 2.61025401e+02 2.14274583e+02 8.90111669e+01
  9.95133256e+03]
 [1.00000000e+01 1.82450343e+02 2.89166581e+02 3.59618151e+01
  9.02199250e+03]
 [1.10000000e+01 1.73848054e+02 2.64833951e+02 2.08466966e+01
  8.40632838e+03]
 [1.20000000e+01 3.21294357e+02 2.52445566e+02 7.73804675e+01
  9.32009035e+03]
 [1.30000000e+01 1.87110680e+02 1.792157

In [35]:
d_df = pd.DataFrame(D)

In [36]:
# Name of the CSV file
filename = 'D.csv'

In [37]:
# Export the DataFrame to a CSV file
d_df.to_csv(filename, index=False)

(b) Generate a data matrix D′ where the rows associate with each
patient, and columns with only anxiety, alcohol_re and diabetes;
respectively. Provide D′ as a csv file.

In [48]:
Dprime = hospital_data[["Anxiety_Di", "Alcohol_re", "Diabetes"]].values

In [76]:
print(Dprime)

[[393.6089968  270.1776041   69.63788301]
 [132.8350144  177.8638329   43.50304521]
 [142.4761626  147.3471426   18.72004792]
 [201.7047303  406.6627627   90.11173856]
 [261.6488435  250.7088222   56.95842035]
 [240.8579466  178.4458509   60.97782955]
 [129.5930109  245.7798483   25.99222493]
 [123.4567901  320.9876543   18.07228916]
 [261.0254013  214.2745831   89.01116686]
 [182.4503425  289.1665806   35.96181509]
 [173.8480536  264.8339507   20.8466966 ]
 [321.2943573  252.4455664   77.38046754]
 [187.1106795  179.2157141   42.36735758]
 [175.294814   326.6857897   38.70145244]
 [223.9966269  189.7383192   43.08642419]
 [169.5736434  123.6740106   39.20338717]
 [530.465048   765.295425   122.2765674 ]
 [108.4206722  184.7167008   42.91510612]
 [300.6943305  250.9430868   59.37660684]
 [260.065498    96.32055481  74.00430571]
 [268.9019138  308.8170417   62.41677763]
 [509.5248809  494.0563243  114.1622017 ]
 [436.0354895  218.6496802  110.4677739 ]
 [169.135565   183.5641914   43.94

In [52]:
dprime_df = pd.DataFrame(Dprime)

In [53]:
# Name of the CSV file
filename = 'Dprime.csv'

In [54]:
# Export the DataFrame to a CSV file
dprime_df.to_csv(filename, index=False)

(c) Generate a matrix G that stores the Euclidean distance between
patient i and j, that is in each entry gij of G the Euclidean distance of row i from row j of D′
is stored. Provide G as a csv
file.
        
        
        (i). Print (in your code) the 5 × 5 sub-matrix G′ of G, where
        g
        ′
        ij = gij for 1 ≤ i, j ≤ 5. Provide the matrix G′
        in your pdf
        file.
        (ii). Find all patients with ‘max’ and ‘min’ distances; separately
        and list them (provide the patient’s ID). Provide the lists in
        your pdf file (carefully explain which list is which).


In [80]:
#C
# compute pairwise Euclidean distances between rows of D_prime
G = cdist(Dprime, Dprime, metric='euclidean')

In [81]:
print(G)

[[  0.         277.86315336 284.16130739 236.37813939 133.98986641
  178.38888533 268.70920112 279.68354699 145.18568001 214.66866577
  225.17550191  74.85839874 227.28682768 227.6210012  189.58854012
  269.40935585 516.37395986 298.91479268  95.4379152  219.26970905
  130.75552398 256.00896176  78.24457946 241.97175202 106.87645915
   92.23381912]
 [277.86315336   0.          40.47736503 243.44272086 148.59489276
  109.42879289  70.21199728 145.66778194 140.81728289 122.09362219
   98.78856668 205.49218633  54.30437543 154.83495956  91.93267423
   65.61059946 713.71618086  25.36469152 183.76424383 154.16623836
  189.79113067 496.8557774  313.17453333  36.74805288 175.29421123
  341.89649849]
 [284.16130739  40.47736503   0.         275.40767519 162.32047871
  111.498095    99.53822235 174.68023192 153.21242016 148.35082268
  121.62182476 215.55201291  59.72471182 183.40848058  95.05955105
   41.40359684 736.96635448  56.05052317 193.43749402 139.59696852
  209.67928622 513.84941666 31

In [82]:
g_df = pd.DataFrame(G)

In [83]:
# Name of the CSV file
filename = 'G.csv'

In [84]:
# Export the DataFrame to a CSV file
g_df.to_csv(filename, index=False)

In [85]:
#(i).
#code will slice the matrix G to create a new matrix G_prime containing the 5x5 sub-matrix 
Gprime = G[:5, :5]

In [86]:
print(Gprime)

[[  0.         277.86315336 284.16130739 236.37813939 133.98986641]
 [277.86315336   0.          40.47736503 243.44272086 148.59489276]
 [284.16130739  40.47736503   0.         275.40767519 162.32047871]
 [236.37813939 243.44272086 275.40767519   0.         170.33517186]
 [133.98986641 148.59489276 162.32047871 170.33517186   0.        ]]


In [105]:
#(ii).
# find patients with maximum distance
max_distance = np.max(G)
max_distance_tuple = np.argwhere(G == max_distance)
max_distance_patients = [(D[a][0], D[b][0]) for a, b in max_distance_tuple]

print("Patients with maximum distance:")
for eachmaxpatient in max_distance_patients:
    print("ID:", eachmaxpatient[0])
   # print("ID:", eachmaxpatient[1])
    ##print("distance:", max_distance)
    

# find patients with minimum distance
min_distance = np.min(G[G > 0])
min_distance_tuple = np.argwhere(G == min_distance)
min_distance_patients = [(D[a][0], D[b][0]) for a, b in min_distance_tuple]

print("\nPatients with minimum distance:")
for eachminpatient in min_distance_patients:
    print("ID:", eachminpatient[0])
   # print("ID:", eachminpatient[1])

Patients with maximum distance:
ID: 16.0
ID: 17.0

Patients with minimum distance:
ID: 13.0
ID: 24.0
